In [17]:
from collections import abc
my_dict = {}
isinstance(my_dict, abc.Mapping)

True

In [14]:
a = dict(one=1, two=2, three=3)
b = {'one': 1, 'two':2, 'three':3}
c = dict(zip(['one', 'two', 'three'], [1, 2, 3]))
d = dict([('two', 2), ('one', 1), ('three', 3)])
a == b == c == d 

True

In [15]:
DIAL_CODES = [
    (86, 'China'),
    (91, 'India'),
    (1, 'United States'),
    (62, 'Indonisia'),
    (55, 'Brazil'),
    (92, 'Pakistan'),
    (880, 'Bangladesh'),
    (234, 'Nigeria'),
    (7, 'Russia'),
    (81, 'Japan')
]
country_code = {country: code for code, country in DIAL_CODES}
country_code

{'China': 86,
 'India': 91,
 'United States': 1,
 'Indonisia': 62,
 'Brazil': 55,
 'Pakistan': 92,
 'Bangladesh': 880,
 'Nigeria': 234,
 'Russia': 7,
 'Japan': 81}

In [16]:
{code: country.upper() for country, code in country_code.items() if code < 66}

{1: 'UNITED STATES', 62: 'INDONISIA', 55: 'BRAZIL', 7: 'RUSSIA'}

In [21]:
class StrKeyDict0(dict):
    
    def __missing__(self, key):
        if isinstance(key, str):
            raise KeyError(key)
        return self[str(key)]
    
    def get(self, key, default=None):
        try:
            return self[key]
        except KeyError:
            return default
        
    def __contains__(self, key):
        return key in self.keys() or str(key) in self.keys()
    
d = StrKeyDict0([('2','two'), ('4', 'four')])
d['2']

'two'

In [22]:
d[4]

'four'

In [23]:
d[1]

KeyError: '1'

In [25]:
d.get('2')

'two'

In [26]:
d.get(4)

'four'

In [27]:
d.get(1, 'N/A')

'N/A'

In [28]:
2 in d

True

In [29]:
1 in d

False

In [30]:
ct = collections.Counter('abracadabra')
ct

Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})

In [33]:
ct.update('aaaaazzz')
ct

Counter({'a': 20, 'b': 2, 'r': 2, 'c': 1, 'd': 1, 'z': 9})

In [34]:
ct.most_common(2)

[('a', 20), ('z', 9)]

In [37]:
import numpy as np
l = np.arange(12)
np.argmin(l)

0

In [38]:
l = np.arange(12).reshape(3, 4)
l

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.argmin(l, axis=0)

array([0, 0, 0, 0])

In [41]:
np.argmin(l, axis=1)

array([0, 0, 0])

AttributeError: module 'numpy' has no attribute 'darray'

In [44]:
from types import MappingProxyType
d = {1: 'A'}
d_proxy = MappingProxyType(d)
d_proxy

mappingproxy({1: 'A'})

In [45]:
d_proxy[1]

'A'

In [46]:
d_proxy[2] = 'x'

TypeError: 'mappingproxy' object does not support item assignment

In [47]:
d[2] = 'B'

In [48]:
d_proxy

mappingproxy({1: 'A', 2: 'B'})

In [49]:
d_proxy[2]

'B'

In [50]:
l = ['spam', 'spam', 'eggs', 'spam']
set(l)

{'eggs', 'spam'}

In [51]:
list(set(l))

['spam', 'eggs']

In [54]:

frozenset(range(10))

frozenset({0, 1, 2, 3, 4, 5, 6, 7, 8, 9})

In [55]:
from unicodedata import name
{chr(i) for i in range(32, 256) if 'SIGN' in name(chr(i), '')}

{'#',
 '$',
 '%',
 '+',
 '<',
 '=',
 '>',
 '¢',
 '£',
 '¤',
 '¥',
 '§',
 '©',
 '¬',
 '®',
 '°',
 '±',
 'µ',
 '¶',
 '×',
 '÷'}

In [74]:
import sys

MAX_BITS = len(format(sys.maxsize, 'b'))

print("%s-bit Python build" % (MAX_BITS + 1))

def hash_diff(o1, o2):
    h1 = '{:>0{}n}'.format(hash(o1), MAX_BITS)
    h2 = '{:>0{}b}'.format(hash(o2), MAX_BITS)
    diff = ''.join('!' if b1 != b2 else ' ' for b1, b2 in zip(h1, h2))
    count = '!= {}'.format(diff.count('!'))
    widt = max(len(repr(o1)), len(repr(o2)), 8)
    sep = '-' * (widt * 2 + MAX_BITS)
    return '{!r:{width}} {}\n{:{width}} {} {}\n{!r:{width}} {}\n{}'.format(
        o1, h1, ' ' * widt, diff, count, o2, h2, sep, width=widt)

if __name__ == '__main__':
    print(hash_diff(1, 1.0))
    print(hash_diff(1.0, 1.0001))
    print(hash_diff(1.0001, 1.0002))
    print(hash_diff(1.0002, 1.0003))

64-bit Python build
1        000000000000000000000000000000000000000000000000000000000000001
                                                                         != 0
1.0      000000000000000000000000000000000000000000000000000000000000001
-------------------------------------------------------------------------------
1.0      000000000000000000000000000000000000000000000000000000000000001
                        !! !   !! !! !!!   ! !!! ! !!   !!!   !          != 21
1.0001   000000000000000110100011011011100010111010110001110001000000001
-------------------------------------------------------------------------------
1.0001   000000000000000000000000000000000000000000000000230584300921345
                       !! !   !! !! !!!   ! !!! ! !!   !!!! !!!!  !!!!!! != 31
1.0002   000000000000001101000110110111000101110101100011100010000000001
-------------------------------------------------------------------------------
1.0002   000000000000000000000000000000000000000000000000461168601

In [79]:
# dial codes of the top ten most populous countries
DIAL_CODES = [
    (86, 'China'),
    (91, 'India'),
    (1, 'United States'),
    (62, 'Indonisia'),
    (55, 'Brazil'),
    (92, 'Pakistan'),
    (880, 'Bangladesh'),
    (234, 'Nigeria'),
    (7, 'Russia'),
    (81, 'Japan')
]

d1 = dict(DIAL_CODES)
print('d1: ', d1.keys())
d2 = dict(sorted(DIAL_CODES))
print("d2: ", d2.keys())
d3 = dict(sorted(DIAL_CODES, key=lambda x:x[1]))
print('d3: ', d3.keys())
assert d1 == d2 and d2 == d3

d1:  dict_keys([86, 91, 1, 62, 55, 92, 880, 234, 7, 81])
d2:  dict_keys([1, 7, 55, 62, 81, 86, 91, 92, 234, 880])
d3:  dict_keys([880, 55, 86, 91, 62, 81, 234, 92, 7, 1])
