In [1]:
x = 'ABC'
dummy = [ord(x) for x in x]
x

'ABC'

In [2]:
dummy

[65, 66, 67]

In [4]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('black', 'S'),
 ('black', 'M'),
 ('black', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [5]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [6]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    

BRA/CE342567
ESP/XDA205856
USA/31195855


In [7]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [8]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
latitude


33.9425

In [9]:
longitude

-118.408056

In [10]:
divmod(20, 8)

(2, 4)

In [11]:
t = (20, 8)
divmod(*t)

(2, 4)

In [12]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [13]:
import os
_, filename = os.path.split('/home/wu/sss.h')
filename

'sss.h'

In [14]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [15]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [16]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [17]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [19]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico city', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('San Paulo', 'BR', 19.649, (-23.547778, -46.635833))
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico city     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
San Paulo       |  -23.5478 |  -46.6358


In [21]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [22]:
tokyo.population

36.933

In [23]:
tokyo.coordinates

(35.689722, 139.691667)

In [24]:
tokyo[1]

'JP'

In [25]:
City._fields

('name', 'country', 'population', 'coordinates')

In [26]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))
delhi = City._make(delhi_data)
delhi._asdict()

OrderedDict([('name', 'Delhi NCR'),
             ('country', 'IN'),
             ('population', 21.935),
             ('coordinates', LatLong(lat=28.613889, long=77.208889))])

In [27]:
for key, value in delhi._asdict().items():
    print(key + ":", value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


In [28]:
s = 'bicycle'
s[::3]

'bye'

In [29]:
s[::-1]

'elcycib'

In [30]:
s[::-2]

'eccb'

In [31]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [32]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [33]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [35]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [36]:
l[2:5] = 100

TypeError: can only assign an iterable

In [37]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [38]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [39]:
5 * 'abc'

'abcabcabcabcabc'

In [40]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [41]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [42]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [43]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [44]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [45]:
board[2][0] = 'Y'
board

[['_', '_', '_'], ['_', '_', '_'], ['Y', '_', '_']]

In [46]:
l = [1, 2, 3]
id(l)

139734082420040

In [47]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [48]:
id(l)

139734082420040

In [49]:
t = (1, 2, 3)
id(t)

139734082809792

In [50]:
t *= 2
t

(1, 2, 3, 1, 2, 3)

In [51]:
id(t)

139734082304136

In [1]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [2]:
t

(1, 2, [30, 40, 50, 60])

In [3]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [4]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [5]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [6]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [7]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [8]:
fruits.sort()

In [9]:
fruits

['apple', 'banana', 'grape', 'raspberry']

In [17]:
import bisect
import sys

HAYSTACK = [1,4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23,29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}     {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        print(ROW_FMT.format(needle, position, offset))
        
if __name__ == '__main__':
    
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect
    
    print('DEMO:', bisect_fn.__name__)
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14       |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14       |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13       |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11       |  |  |  |  |  |  |  |  |  |  |23
22 @  9       |  |  |  |  |  |  |  |  |22
10 @  5       |  |  |  |  |10
 8 @  5       |  |  |  |  |8 
 5 @  3       |  |  |5 
 2 @  1       |2 
 1 @  1       |1 
 0 @  0     0 


In [19]:
def grade(score, breakpoints=[60, 70, 80, 90], grades='FDCBA'):
    i = bisect.bisect(breakpoints, score)
    return grades[i]

[grade(score) for score in [33, 99, 77, 70, 89, 90, 100]]

['F', 'A', 'C', 'C', 'B', 'A', 'A']

In [20]:
import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)

10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


In [21]:
from array import array
from random import random
floats = array('d', (random() for i in range(10 ** 7)))
floats[-1]

0.5963321947530882

In [22]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [24]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats.fromfile(fp, 10 ** 7)
fp.close()
floats2

array('d')

In [26]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [27]:
memv[0]

-2

In [28]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [29]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [30]:
import numpy

In [31]:
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
type(a)

numpy.ndarray

In [33]:
a.shape

(12,)

In [34]:
a.shape = 3, 4

In [35]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
a[2]

array([ 8,  9, 10, 11])

In [37]:
a[2, 1]

9

In [38]:
a[: 1]

array([[0, 1, 2, 3]])

In [39]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [40]:
from collections import deque
dq = deque(range(10), maxlen=10)

In [41]:
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [43]:
dq.rotate(-4)

In [44]:
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [45]:
dq.appendleft(-1)

In [46]:
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
dq.extend([11, 22, 33])

In [48]:
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33])

In [49]:
dq.extendleft([10, 20, 30, 40])

In [50]:
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])

In [51]:
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19]
sorted(l, key=int)

[0, '1', 5, 6, '9', 14, 19, '23', 28, '28']

In [52]:
sorted(l, key=str)

[0, '1', 14, 19, '23', 28, '28', 5, 6, '9']

In [53]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
